spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/escape_game_db
    username: escape_user
    password: escape1234
    driver-class-name: org.mariadb.jdbc.Driver

  web:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  data:
    redis:
      host: localhost
      port: 6379

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


file:
  upload:
    base-dir: ./uploads     # 실제 파일 저장 경로
    url-prefix: http://localhost:8081/uploads

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.hkouo.rebind.model
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

logging:
  level:
    root: INFO
    com.hkouo.rebind.mapper: DEBUG         # 본인 Mapper 패키지
    org.apache.ibatis: DEBUG               # MyBatis 내부
    org.mybatis: DEBUG                     # MyBatis 설정
    jdbc.sqlonly: DEBUG                    # (p6spy 등 외부 SQL 로그 툴용)
    jdbc.sqltiming: DEBUG
